import fs from "fs/promises";
import path from "path";
import { PrismaClient } from "@/app/generated/prisma/client";
import { matchIssueToLessons, type MatchableLesson } from "./knowledge-matcher";

export interface AdvisoryResult {
  projectsScanned: number;
  advisoriesWritten: number;
  advisories: { project: string; lessonTitle: string; category: string }[];
}

/**
 * Build advisory markdown content.
 */
function buildAdvisoryContent(
  matches: { lessonTitle: string; category: string; severity: string; matchedKeywords: string[] }[],
  issueContext: string
): string {
  const lines = [
    "# Nerve Center Advisory",
    "",
    `Generated: ${new Date().toISOString().split("T")[0]}`,
    "",
    `## Context`,
    issueContext,
    "",
    "## Matched Knowledge Lessons",
    "",
  ];

  for (const match of matches) {
    lines.push(`### ${match.lessonTitle}`);
    lines.push(`- **Category:** ${match.category}`);
    lines.push(`- **Severity:** ${match.severity}`);
    lines.push(`- **Matched on:** ${match.matchedKeywords.join(", ")}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "_This advisory was auto-generated by Cascade. " +
      "Rename to nerve-center-advisory-read.md after reviewing._"
  );

  return lines.join("\n");
}

/**
 * Scan all registered projects for issues and generate advisories
 * when matching knowledge lessons are found.
 */
export async function generateAdvisories(
  prisma: PrismaClient
): Promise<AdvisoryResult> {
  const [projects, allLessons] = await Promise.all([
    prisma.project.findMany(),
    prisma.knowledgeLesson.findMany(),
  ]);

  const matchableLessons: MatchableLesson[] = allLessons.map((l) => ({
    id: l.id,
    title: l.title,
    content: l.content,
    tags: l.tags,
    category: l.category,
    severity: l.severity,
  }));

  const result: AdvisoryResult = {
    projectsScanned: projects.length,
    advisoriesWritten: 0,
    advisories: [],
  };

  for (const project of projects) {
    // Gather issue context from health details and debt
    let issueContext = "";
    try {
      const details = JSON.parse(project.healthDetails);
      if (details.debtItems?.length > 0) {
        issueContext += details.debtItems.join(". ") + ". ";
      }
    } catch {
      // no details
    }

    if (project.health === "blocked" || project.health === "warning") {
      issueContext += `Project health: ${project.health}. Phase: ${project.currentPhase}. `;
    }

    if (!issueContext.trim()) continue;

    // Match against knowledge
    const matches = matchIssueToLessons(issueContext, matchableLessons, 2);

    if (matches.length === 0) continue;

    // Write advisory file
    const advisoryDir = path.join(project.path, ".claude");
    const advisoryPath = path.join(advisoryDir, "nerve-center-advisory.md");

    try {
      await fs.mkdir(advisoryDir, { recursive: true });
      const content = buildAdvisoryContent(
        matches.map((m) => ({
          lessonTitle: m.lessonTitle,
          category: m.category,
          severity: m.severity,
          matchedKeywords: m.matchedKeywords,
        })),
        issueContext.trim()
      );
      await fs.writeFile(advisoryPath, content, "utf-8");

      // Log activity event
      await prisma.activityEvent.create({
        data: {
          projectId: project.id,
          eventType: "advisory-sent",
          summary: `Advisory: ${matches.map((m) => m.lessonTitle).join(", ")}`,
        },
      });

      result.advisoriesWritten++;
      for (const m of matches) {
        result.advisories.push({
          project: project.name,
          lessonTitle: m.lessonTitle,
          category: m.category,
        });
      }
    } catch {
      // Skip if can't write to project dir
    }
  }

  return result;
}
